# from https://docs.travis-ci.com/user/languages/python/
dist: xenial # needed for Python 3.7+: https://docs.travis-ci.com/user/reference/xenial/#python-support
language: python
python:
  - "2.7"  # Oldest Python supported by Travis xenial
  - "3.4"  # Oldest Python 3.x supported by Travis xenial
  - "3.7"  # Latest non-dev Python, as of Jun 2019.
  - "3.8-dev" # development Python
  # PyPy versions
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
# command to install dependencies
install:
  - pip install -U sympy
#  - pip install coverage
#  - pip install codecov
# We generally don't need to install matplotlib for the test.
#  - pip install -r requirements.txt
# command to run tests
script: BSSN/test/run_NRPy_UnitTests.sh
# After completion, push results to codecov
#after_success:
#  - codecov
