# from https://docs.travis-ci.com/user/languages/python/
language: python
python:
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install sympy
# We generally don't need to install matplotlib for the test.
#  - pip install -r requirements.txt
# command to run tests
script: BSSN/test/run_BSSN_tests.sh
